### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by itqbtknzn** [wesleysliao/ros2_lifecycle_py#1]
Hello, I have one question related alignment of your repository with ros2 lifecycle usage:  such as using ros2 lifecyle set /lc_talker configure and etc. Is your comment are allign with C++ usage of life cycle manager while,

When I run this :
**_ros2 run ros2_lifecycle_py demo_talker_** 

and enter this: 
**_ros2 lifecycle set /lc_talker configure_**

I got this error 
**_ros2 run ros2_lifecycle_py demo_talker 
Traceback (most recent call last):
  File "/home/btknzn/ros_test/install/ros2_lifecycle_py/lib/ros2_lifecycle_py/demo_talker", line 33, in <module>
    sys.exit(load_entry_point('ros2-lifecycle-py==0.0.0', 'console_scripts', 'demo_talker')())
  File "/home/btknzn/ros_test/install/ros2_lifecycle_py/lib/python3.10/site-packages/ros2_lifecycle_py/lifecycle_talker.py", line 47, in main
    rclpy.spin(lifecycle_talker)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/__init__.py", line 222, in spin
    executor.spin_once()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 713, in spin_once
    raise handler.exception()
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/task.py", line 239, in __call__
    self._handler.send(None)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 418, in handler
    await call_coroutine(entity, arg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 372, in _execute_service
    response = await await_or_execute(srv.callback, request, srv.srv_type.Response())
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/executors.py", line 107, in await_or_execute
    return callback(*args)
  File "/home/btknzn/ros_test/install/ros2_lifecycle_py/lib/python3.10/site-packages/ros2_lifecycle_py/lifecycle.py", line 153, in get_available_transitions
    response.available_transitions = self.available_transitions
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/lifecycle_msgs/srv/_get_available_transitions.py", line 231, in available_transitions
    assert \
AssertionError: The 'available_transitions' field must be a set or sequence and each value of type 'TransitionDescription'
[ros2run]: Process exited with failure 1_**

**_but  when I run this: 
ros2 run lifecycle lifecycle_talker_**
and run this : 
ros2 lifecycle set /lc_talker configure
everything works fine, I did not understand the reason of the firs problem

I think there is a discrepancy between the Python implementation of the ROS2 Lifecycle node and its C++ counterpart.

**Comment by itqbtknzn** [comment]
Additionally, I can only use your code with this comments: 

ros2 service call /NODE_NAME/change_state lifecycle_msgs/srv/ChangeState "{transition: {id: 1}}"
ros2 service call /NODE_NAME/change_state lifecycle_msgs/srv/ChangeState "{transition: {id: 3}}"
